"""add session table

Revision ID: 233e6cf7eab5
Revises: 2911f3654427
Create Date: 2026-06-02 10:48:36.336201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233e6cf7eab5'
down_revision = '2911f3654427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('stack', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
