"""empty message

Revision ID: 494e20b27bab
Revises: effcd837c83d
Create Date: 2026-06-21 12:27:36.246686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494e20b27bab'
down_revision = 'effcd837c83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resetToken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resetToken', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resetToken')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resetToken')
    # ### end Alembic commands ###
