"""add Question table

Revision ID: 913e0ad60d04
Revises: 233e6cf7eab5
Create Date: 2026-06-02 11:04:51.565344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913e0ad60d04'
down_revision = '233e6cf7eab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
