"""add is_completed to session

Revision ID: 9f02a2797932
Revises: b2c3d4e5f6a7
Create Date: 2026-06-17 12:50:58.358882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f02a2797932'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))

    # ### end Alembic commands ###


def downgrade():
    # ### end Alembic commands ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
