"""add code and code_language to card

Revision ID: e1297814b3c4
Revises: 768878a8b974
Create Date: 2026-06-05 12:25:12.764328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1297814b3c4'
down_revision = '768878a8b974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('code_language', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('code_language')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
